### ISSUE TITLE
A small suggestion, slug is currently limited to lowercase characters, and the error message only says the wrong format, a more precise error message can be given.

### ISSUE THREAD

**Issue by s87343472** [qiayue/GitBase#2]
A small suggestion, slug is currently limited to lowercase characters, and the error message only says the wrong format, a more precise error message can be given.
<img width="416" alt="image" src="https://github.com/user-attachments/assets/54788412-82aa-4669-abae-5f5254823ac0">

**Comment by qiayue** [comment]
As part of the URL, slug can only be lowercase and cannot have spaces.
The prompts here are not very friendly at present, and can be improved later.
In addition, after connecting to AI later, slug should be generated by AI.
