### ISSUE TITLE
Licensing Information Missing for GitBase

### ISSUE THREAD

**Issue by waleed-durrani** [qiayue/GitBase#3]
Hi @qiayue, The project looks great. I truly appreciate the work.

**The Problem:**
The GitBase's ReadME states it’s open-source under the MIT license, but the [provided link](https://github.com/qiayue/GitBase?tab=readme-ov-file#license) returns a 404 error. Please update the link or confirm the open-source license status.

Thanks!

Waleed Durrani
**_[Creator of InsTech Newsletter](https://www.linkedin.com/in/muhammad-w/)_**

**Comment by qiayue** [comment]
Hi, I made a mistake before and now I have added the MIT license.

**Comment by waleed-durrani** [comment]
Great, thanks a lot @qiayue. By the way, the reason I specifically asked for the license was; I wanted to feature your tool in my **[#InsTechNewsletter](https://www.linkedin.com/pulse/latest-under-the-radar-9-tools-you-need-know-from-instechs-waleed-fxl8f)** as an Open Source Tool.

Please do check it out. Your tool is amazing 🚀.
